--DROP VIEW V_StageSet;

CREATE VIEW V_StageSet as
SELECT DISTINCT
	D.[ID],
	COALESCE(C.Status,D.Status) as Status,
	COALESCE(C.[Correctie WZC], D.[Aanduiden keuze voor WZC]) as WCZ,
	COALESCE(C.[Correctie Naam en Voornaam],D.[Naam student]) as [Naam student],
	D.[Naam van de school of onderwijsinstelling] as School,
	D.[Naam aanvrager] as Naam_aanvrager,
  	D.[E-mail adres aanvrager] as [Email_aanvrager],
  	D.[Telefoonnummer aanvrager] as Tel_aanvrager,
  	D.[Studierichting/stage] as Studierichting_stage,
  	D.[Studiejaar / Module] as Studiejaar_Module,
  	D.[Specialisatie],
  	D.[Voorkeursafdeling],
  	D.[Totaal aantal stage uren] as stage_uren,
  	D.[Totaal aantal stage dagen] as stage_dagen,
  	D.[Aantal te presteren uren per stage dag] as uren_per_dag,
  	D.[Jaar],
	D.[Maand],
	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[1] END [1],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[2] END [2],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[3] END [3],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[4] END [4],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[5] END [5],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[6] END [6],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[7] END [7],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[8] END [8],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[9] END [9],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[10] END [10],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[11] END [11],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[12] END [12],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[13] END [13],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[14] END [14],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[15] END [15],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[16] END [16],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[17] END [17],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[18] END [18],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[19] END [19],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[20] END [20],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[21] END [21],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[22] END [22],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[23] END [23],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[24] END [24],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[25] END [25],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[26] END [26],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[27] END [27],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[28] END [28],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[29] END [29],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[30] END [30],
  	CASE WHEN C.Status in ('Niet OK','Fout') THEN 0 ELSE D.[31] END [31]
From  Schema_CorrectieFile  C
INNER JOIN Schema_DataSet_2022 D on C.ID=D.ID
WHERE C.ID > 0
AND NOT Jaar is null
--and Jaar >= strftime('%Y',date('now'))